column_width = 200
line_endings = 'Unix'
indent_type = 'Spaces' # Unix, Window
indent_width = 4
quote_style = 'AutoPreferSingle' # AutoPreferDouble, AutoPreferSingle, ForceDouble, ForceSingle
call_parentheses = 'None' # Always, NoSingleString, NoSingleTable, None, Input
collapse_simple_statement = 'Always' # Never, FunctionOnly, ConditionalOnly, Always

[sort_requires]
enabled = true
